version: '3.4'

services:
  catalogDb:
    container_name: catalogDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 

  basketDb:
    container_name: basketDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/


  distributedCache:
    container_name: distributedCache
    restart: always
    ports: 
      - "6379:6379"

  orderDb:
    container_name: orderDb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!!VeryStrongPassword!!
    ports:
      - 1433:1433

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__CatalogDb=User ID=postgres;Password=postgres;Server=catalogDb;Port=5432;Database=CatalogDb;Pooling=true;Include Error Detail=true;

    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - catalogDb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__BasketDb=Server=basketDb;Port=5432;Database=BasketDb;User ID=postgres;Password=postgres;Pooling=true;Include Error Detail=true
      - ConnectionStrings__Redis=distributedCache:6379
      - DiscountGRPC__Address= https://discount.grpc:8081
    ports:
      - "6001:8080"
      - "6061:8081"
    depends_on:
      - basketDb
      - distributedCache
      - discount.grpc
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DiscountDb=Data Source= discountDb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
